name: chunk-adaptive-restoration
channels:
  - defaults
dependencies:
  - python=3.8.5
  - numpy
  - scikit-learn
  - pip
  - matplotlib
  - tqdm
  - pandas
  - pip:
    - stream-learn
    - imbalanced-learn
